import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "@/component/utils/slider";
import { fetchAllProducts } from "@/services/apis/ServerSide";
import ProductPage from "@/component/Product/ProductPage";

export default function Home(props) {
  console.log("props....", props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Slider />
        <ProductPage products={props.products?.products} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    const response = await fetchAllProducts();

    return {
      props: {
        products: response.data,
      },
    };
  } catch (err) {
    return {
      props: {
        products: null,
      },
    };
  }
}
